FROM node:16-alpine

WORKDIR /app
RUN mkdir common
COPY common/package.json common
COPY common/package-lock.json common
WORKDIR /app/common
RUN npm install --silent

WORKDIR /app
RUN mkdir collect-tweets
COPY collect-tweets/package.json collect-tweets
COPY collect-tweets/package-lock.json collect-tweets
WORKDIR /app/collect-tweets
RUN npm install --silent

CMD ["npm", "start"]