FROM node:18-alpine

WORKDIR /app
COPY common common
COPY collect-tweets collect-tweets

WORKDIR /app/common
RUN apk add --no-cache --virtual .gyp python3 make g++ \
    && apk update \
    && npm ci && npm cache clean --force \
    && apk del .gyp

WORKDIR /app/collect-tweets
RUN apk add --no-cache --virtual .gyp python3 make g++ \
    && apk update \
    && npm ci && npm cache clean --force \
    && apk del .gyp
CMD ["npm", "start"]