#   port mappings
#
#   service         local -> host
#   ------------------------------
#   mongo           27017 -> 8283
#   mongo-express   8081  -> 8282
#   api             5000  -> 8281
#   web             3000  -> 8280

version: '3.3'
services:
  # Database
  mongo:
    image: mongo:5.0-focal
    ports:
      - '8283:27017'
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: 'no'
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    ports:
      - '8282:8081'
    restart: 'no'

  # API
  api:
    links:
      - mongo
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      - api-node-modules:/app/node_modules
    environment:
      HOST: '0.0.0.0'
      PORT: 5000
      MONGO_URI: 'mongodb://mongo:27017/defi'
    ports:
      - '8281:5000'
    restart: 'no'

  # Web
  web:
    depends_on:
      - api
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app
      - web-node-modules:/app/node_modules
    environment:
      NODE_ENV: 'developement'
    ports:
      - '8280:3000'
    restart: 'no'
    stdin_open: true

  # Services
  bootstrap:
    depends_on:
      - mongo
    links:
      - mongo
    build:
      context: ./services
      dockerfile: ./bootstrap/Dockerfile.dev
    volumes:
      - ./services:/app
      - common-node-modules:/app/common/node_modules
      - bootstrap-node-modules:/app/bootstrap/node_modules
    environment:
      MONGO_URI: 'mongodb://mongo:27017/defi'
      API_URL: 'https://api.llama.fi/protocols'
      DELAY_MS: 86400000
    restart: 'no'

  collect-tweets:
    depends_on:
      - mongo
      - bootstrap
    links:
      - mongo
    build:
      context: ./services
      dockerfile: ./collect-tweets/Dockerfile.dev
    volumes:
      - ./services:/app
      - common-node-modules:/app/common/node_modules
      - collect-tweets-node-modules:/app/collect-tweets/node_modules
    environment:
      MONGO_URI: 'mongodb://mongo:27017/defi'
      STARTUP_DELAY_MS: 10000
      REQUEST_DELAY_MS: 10000
      INTERVAL_DELAY_MS: 60000
      BEARER_KEY: ${TWITTER_BEARER_KEY}
      MAX_RESULTS: 100
    restart: 'no'

  collect-protocols:
    depends_on:
      - mongo
      - bootstrap
    links:
      - mongo
    build:
      context: ./services
      dockerfile: ./collect-protocols/Dockerfile.dev
    volumes:
      - ./services:/app
      - collect-protocols-node-modules:/app/collect-protocols/node_modules
      - common-node-modules:/app/common/node_modules
    environment:
      NODE_ENV: 'development'
      MONGO_URI: 'mongodb://mongo:27017/defi'
      API_URL: 'https://rapidapi.com/coingecko/api/coingecko'
      REQUEST_DELAY_MS: 1000
      INTERVAL_DELAY_MS: 86400000
      STARTUP_DELAY_MS: 10000
    restart: 'no'

volumes:
  mongo-data:
  mongo-config:
  api-node-modules:
  web-node-modules:
  common-node-modules:
  bootstrap-node-modules:
  collect-tweets-node-modules:
  collect-protocols-node-modules:
