FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    locales \
    python3-pip \
    python3-setuptools && \
    pip3 install --upgrade pip setuptools

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /app
COPY requirements.txt .
RUN pip3 install --timeout=900 --no-cache-dir -r requirements.txt --quiet

CMD ["uvicorn", "run:app", "--reload", "--host", "0.0.0.0"]