FROM node:16-alpine

WORKDIR /app
RUN mkdir common
COPY common/package.json common
WORKDIR /app/common
RUN npm install --silent

WORKDIR /app
RUN mkdir collect-protocols
COPY collect-protocols/package.json collect-protocols
WORKDIR /app/collect-protocols
RUN npm install --silent

CMD ["npm", "run", "dev"]