FROM node:18-alpine
WORKDIR /app
COPY package.json .
RUN npm install --silent
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache
ARG REACT_APP_AMPLITUDE_API_KEY
ENV REACT_APP_AMPLITUDE_API_KEY $REACT_APP_AMPLITUDE_API_KEY
CMD ["npm", "start"]
